name: clima
description: Um aplicativo de clima baseado em localização feito no Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^6.1.0
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1
  weather: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
